services:
  # Uygulama Servisi (API)
  app:
    build: .  # Mevcut klasördeki Dockerfile'ı kullan
    container_name: hackathon_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env  # Ortam değişkenlerini buradan oku
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app

  # Veritabanı Servisi
  db:
    image: postgres:16-alpine
    container_name: hackathon_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis - Cache
  redis:
      image: redis:7-alpine
      container_name: hackathon_redis
      restart: always
      ports:
        - "6379:6379"
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5

  worker:
      build: .
      container_name: hackathon_worker
      command: celery -A app.core.config.celery.celery_app worker --loglevel=info
      env_file:
        - .env
      environment:
        - POSTGRES_SERVER=db
        - REDIS_URL=redis://redis:6379/0
        # Docker içinde 'redis' hostname'ini kullanması için eziyoruz:
        - CELERY_BROKER_URL=redis://redis:6379/1
        - CELERY_RESULT_BACKEND=redis://redis:6379/2
      depends_on:
        redis:
          condition: service_healthy
        db:
          condition: service_healthy
      # Hot-reload için kodu bağlıyoruz (Opsiyonel ama geliştirmede iyi)
      volumes:
        - ./app:/app/app

      # 2. Flower (İzleme Paneli)
  flower:
        build: .
        container_name: hackathon_flower
        command: celery -A app.core.config.celery.celery_app flower --port=5555
        ports:
          - "5555:5555" # Tarayıcıdan erişim için
        env_file:
          - .env
        environment:
          - CELERY_BROKER_URL=redis://redis:6379/1
          - CELERY_RESULT_BACKEND=redis://redis:6379/2
        depends_on:
          - redis
          - worker

  dozzle:
    image: amir20/dozzle:latest
    container_name: hackathon_dozzle
    restart: always
    volumes:
      # Docker'ın kalbine (soketine) bağlanıp logları okuması için şart
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080" # Tarayıcıdan 8888 portuyla erişeceğiz

volumes:
  postgres_data:
